### ISSUE TITLE
compiling issues

### ISSUE THREAD

**Issue by ivorivorhepl** [brightfyregit/Indie-Cross-Public#10]
how do i fix this lmao

source/MainMenuState.hx:261: characters 35-61 : Cannot execute `git rev-parse HEAD`. fatal: not a git repository (or any of the parent directories): .git
source/MainMenuState.hx:261: characters 35-61 : ...

i did not even touch anything either

**Comment by Zoardedz** [comment]
you can delete that, it was used for when the mod was being made to automatically do git shit (i assume)

**Comment by ivorivorhepl** [comment]
oh okay thanks lol
