### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by TheGaloXx** [brightfyregit/Indie-Cross-Public#12]
First I got the bink2dll, I just deleted it
Then the "Cannot execute git rev-parse HEAD. fatal: not a git repository (or any of the parent directories): .git", I deleted it too

Now I got this:

Error: Main.cpp
export\debug\windows\obj\include\openfl/events/ErrorEvent.h(51): error C2059: syntax error: 'constant'
export\debug\windows\obj\include\openfl/events/ErrorEvent.h(51): error C2238: unexpected tokens before ';'

**Comment by TheGaloXx** [comment]
I forgot the GJKeys problem, Im trying to fix it

**Comment by RonyxDumb** [comment]
I only get the Main.cpp error

**Comment by TheGaloXx** [comment]
I solved it, just delete everything related to ErrorEvent.
There’s probably something that doesn’t work now but at least the game works.

**Comment by RonyxDumb** [comment]
So...you delete Error event?

**Comment by TheGaloXx** [comment]
> So...you delete Error event?

Yeah, there’s a few .hx where ErrorEvent is used, just delete the code it is involved in.
