### ISSUE TITLE
Compiling errors in Main.cpp

### ISSUE THREAD

**Issue by Similirity** [brightfyregit/Indie-Cross-Public#13]
I'm getting this error while I'm compiling causing it to completely stop the process and I'm just not sure what to do.

Error: Main.cpp
"include\openfl/events/ErrorEvent.h(51): error C2059: syntax error: 'constant'"
"include\openfl/events/ErrorEvent.h(51): error C2238: unexpected token(s) preceding ';'"

Thanks.

**Comment by RonyxDumb** [comment]
Same error

**Comment by Similirity** [comment]
Ok i found the error, basically just delete every line of code associated with errorevent

**Comment by RonyxDumb** [comment]
Thx

**Comment by polybiusproxy** [comment]
> Ok i found the error, basically just delete every line of code associated with errorevent

That breaks the crash handler, not recommended.
