### ISSUE TITLE
what is Bink2DLL

### ISSUE THREAD

**Issue by ADA-Funni** [brightfyregit/Indie-Cross-Public#14]
Documents\Indie-Cross-Public>lime test windows
Error: Could not find asset path "tools/Bink2DLL/"

**Comment by MemeHoovy** [comment]
It's an old and unused library that (I've heard) was suppost to make videos run better.
Just remove it from the project.xml file.

**Comment by Zoardedz** [comment]
bink is a video playing dll and shit from RAD Game tools http://www.radgametools.com/bnkmain.htm

**Comment by REALHaydenGaming** [comment]
if you don't know, it's: YOUR BALLS

**Comment by MemeHoovy** [comment]
> if you don't know, it's: YOUR BALLS

:trollface:

**Comment by REALHaydenGaming** [comment]
> > if you don't know, it's: YOUR BALLS
> 
> :trollface:

😭 - children dumb asf
