### ISSUE TITLE
this error

### ISSUE THREAD

**Issue by jmxamongusmodder** [brightfyregit/Indie-Cross-Public#19]
- src/flixel/util/_FlxSignal/Macro.cpp
Error: Main.cpp
include\openfl/events/ErrorEvent.h(50): error C2059: syntax error: 'constant'
include\openfl/events/ErrorEvent.h(50): error C2238: unexpected token(s) preceding ';'

**Comment by MemeHoovy** [comment]
> * src/flixel/util/_FlxSignal/Macro.cpp
>   Error: Main.cpp
>   include\openfl/events/ErrorEvent.h(50): error C2059: syntax error: 'constant'
>   include\openfl/events/ErrorEvent.h(50): error C2238: unexpected token(s) preceding ';'

just remove everything related to error events in main, something is wrong with the crash handler

**Comment by polybiusproxy** [comment]
only true haxe nerds can fix those issues without removing code 😎

**Comment by MemeHoovy** [comment]
> only true haxe nerds can fix those issues without removing code 😎

k
