### ISSUE TITLE
how do i fix this

### ISSUE THREAD

**Issue by blazingcody** [brightfyregit/Indie-Cross-Public#22]
![Screenshot 2022-09-05 11 59 41 AM](https://user-images.githubusercontent.com/77142352/188485950-41162249-22b8-43d0-8c75-c3498943504d.png)

**Comment by polybiusproxy** [comment]
you don't.
indie cross was never designed to work on linux

**Comment by REALHaydenGaming** [comment]
> you don't. indie cross was never designed to work on linux

fuck you, I will make it work.

**Comment by Squidtito** [comment]
Someone I know made it work for linux, there's quite a loop and repeat process to it..
