### ISSUE TITLE
Third Strum Camo Success

### ISSUE THREAD

**Issue by ChandelureF-5** [brightfyregit/Indie-Cross-Public#23]
I can imagine you intentionally made that third strumline code hard to find so that people couldn't easily port your mod to psych. But, if that was a full coincidence, I bet you'd suggest porting... Basically all of that source over to a psych mod, then sifting through to find the files where third strum resides, thus allowing for the files to be differentiated.

**Comment by MemeHoovy** [comment]
> I can imagine you intentionally made that third strumline code hard to find so that people couldn't easily port your mod to psych. But, if that was a full coincidence, I bet you'd suggest porting... Basically all of that source over to a psych mod, then sifting through to find the files where third strum resides, thus allowing for the files to be differentiated.

just press ctrl f and paste bonedoggle into the search bar, then you should be able to find the code for the 3rd strumline like that

**Comment by Sword352** [comment]
what

**Comment by Sword352** [comment]
dude its easy to find wdym
![image](https://user-images.githubusercontent.com/99792114/222950869-9db03759-5f5f-4d09-8b89-684ad0913ea4.png)
its in playstate, are u sure you know how to code
