### ISSUE TITLE
null object reference 

### ISSUE THREAD

**Issue by ryotasuzui02** [brightfyregit/Indie-Cross-Public#24]
in the official build on gamejolt im getting  null object reference when doing the nightmare songs i have unlocked 
![Screenshot (6)](https://user-images.githubusercontent.com/113819275/190888746-6b2602ee-0c1a-4f1c-a1c4-a3bb0ad50178.png) as you can see with the screenshot. my specs it not the problem, my specs are decent which i have a RTX 3060 and a R5 5600H. thought i should point this out.

**Comment by TNT-King** [comment]
This is not an Indie Cross issue. Ask the dev of GameJolt FNF Integration in: https://github.com/TentaRJ/GameJolt-FNF-Integration
