### ISSUE TITLE
Doesn't work on html5

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [brightfyregit/Indie-Cross-Public#25]

**Comment by MemeHoovy** [comment]
> _No description provided._

so it doesn't...

**Comment by LEVIXDDLMAO** [comment]
we already  knew that

**Comment by REALHaydenGaming** [comment]
LMAFOOOOOOOOOOOOOOOOOO

**Comment by LEVIXDDLMAO** [comment]
huh? bro nobody asked you

**Comment by REALHaydenGaming** [comment]
> huh? bro nobody asked you

If you're making an HTML5 port just for a shitty website.

Fatherless behavior.
