### ISSUE TITLE
Main.cpp error

### ISSUE THREAD

**Issue by ThreeLittleNinjas** [brightfyregit/Indie-Cross-Public#28]
how do I fix this:

Error: Main.cpp
include\openfl/events/ErrorEvent.h(51): error C2059: syntax error: 'constant'
include\openfl/events/ErrorEvent.h(51): error C2238: unexpected token(s) preceding ';'

Please fix this without removing any code.

**Comment by MemeHoovy** [comment]
Delete everything related to errors in Main

**Comment by ThreeLittleNinjas** [comment]
Deleting everything breaks the crash handler

> Delete everything related to errors in Main, and what your asking to do is **not possible**

**Comment by ThreeLittleNinjas** [comment]
> Delete everything related to errors in Main, and what your asking to do is **not possible**

That breaks the crash handler.

**Comment by MemeHoovy** [comment]
that’s the point, it doesn’t work

**Comment by MemeHoovy** [comment]
Just delete the crash handler althougher

**Comment by ThreeLittleNinjas** [comment]
Thanks!!! :)
