### ISSUE TITLE
add sex

### ISSUE THREAD

**Issue by stilic** [brightfyregit/Indie-Cross-Public#30]
hey i know you work on todd fnf modd just like me
but
can you add sex to this mod please.................

**Comment by MemeHoovy** [comment]
Uh…..😐 

![29A561B9-0BBC-4B57-900F-B47F67689D85](https://user-images.githubusercontent.com/97995998/203331283-820917a9-7746-4c89-90d6-79659e690e98.gif)

**Comment by Zoardedz** [comment]
why was this opened recently :worried:

**Comment by MemeHoovy** [comment]
lol
