### ISSUE TITLE
Can't Compile (please help)

### ISSUE THREAD

**Issue by COOLDUDE6942021** [brightfyregit/Indie-Cross-Public#31]
i cant compile when i do lime test windows/lime build windows -release
here's what shows up when i try to compile
![image](https://user-images.githubusercontent.com/105100969/207264968-9929bd72-89ec-4b73-93d5-86bf69588885.png)
and yes i did download and installed everything i needed to

**Comment by MemeHoovy** [comment]
use an older version of haxeflixel & flixel addons

**Comment by MemeHoovy** [comment]
don't use flixel 5.0.0 & flixel addons 3

**Comment by COOLDUDE6942021** [comment]
> don't use flixel 5 & flixel addons 3

**Comment by COOLDUDE6942021** [comment]
NVM I FIGURED IT OUT
> use an older version of haxeflixel & flixel addons

how do i get the older versions (im really not that smart, its probably pretty simple

**Comment by MemeHoovy** [comment]
`haxelib install flixel 4.11.0`
`haxelib install flixel-addons 2.11.0`
go look on the haxelib sites for older versions

**Comment by COOLDUDE6942021** [comment]
> `haxelib install flixel 4.11.0` `haxelib install flixel-addons 2.11.0` go look on the haxelib sites for older versions

thanks, but i found out how to, and i got the source code compiled, but thanks for telling me what to do

**Comment by MemeHoovy** [comment]
You’re welcome
