### ISSUE TITLE
cant compile bink2dll

### ISSUE THREAD

**Issue by lemz1** [brightfyregit/Indie-Cross-Public#4]
Could not find asset path "tools/Bink2DLL/"

this is the error i get when i try lime build windows.
idk why
i installed the libraries.

**Comment by lemz1** [comment]
ooh wait i think you guys forgot to add a tools folder

i looked in the project xml and i guess thats the problem

so i guess it isnt a library problem

**Comment by polybiusproxy** [comment]
Unused library, just remove all references of it.
