### ISSUE TITLE
how do I steal the code

### ISSUE THREAD

**Issue by TheShovel** [brightfyregit/Indie-Cross-Public#7]
im really dumb idk how to git clone 🤓 
![image](https://user-images.githubusercontent.com/68913917/183287009-e7cd2b40-44cd-4c2e-a00d-c9af5f5d0768.png)

**Comment by polybiusproxy** [comment]
shut up jodie

**Comment by polybiusproxy** [comment]
:trollface:

**Comment by TheShovel** [comment]
FUCK YOU

**Comment by polybiusproxy** [comment]
> FUCK YOU

:trollface:

**Comment by Chidubemmo** [comment]
There is a button called fork on the top of the page, click it so you can clone the repository, you can modify as much as you want without messing with the og

**Comment by polybiusproxy** [comment]
> There is a button called fork on the top of the page, click it so you can clone the repository, you can modify as much as you want without messing with the og

this is a joke issue lol
