### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by Donothan73** [brightfyregit/Indie-Cross-Public#8]
When Compiling, without even touching the code: 

"source/MainMenuState.hx:262: characters 35-61 : Cannot execute `git rev-parse HEAD`. fatal: not a git repository (or any of the parent directories): .git"

"source/MainMenuState.hx:262: characters 35-61 :source/GameJolt.hx:59: characters 22-28 : Type not found : GJKeys"

**Comment by ghost** [comment]
mhh.. did you just try to remove it?

**Comment by Donothan73** [comment]
Doesn't work

**Comment by RonyxDumb** [comment]
Sad

**Comment by Donothan73** [comment]
I managed to fix the Gamejolt Key error but I dont know what to do about the git issue

**Comment by ghost** [comment]
emh .. then could you tell me how do i solve the Gamejolt key? Pls
Well now I am cloning the reposite so now I see how to fix, then I will let you know

**Comment by Donothan73** [comment]
So I used https://github.com/TentaRJ/GameJolt-FNF-Integration/blob/main/source/GJKeys.hx

You will need to go on Gamejolt and have a game on there unlisted or not, you need the game ID

Download it and add GJKeys to the source folder, add your IDs and then add "import GJKeys;" to Gamejolt.hx at the very top with the rest of the import stuff.

**Comment by Donothan** [comment]
Also you have to add "import GJKeys;"

**Comment by ghost** [comment]
OK thanks!

**Comment by Donothan73** [comment]
np

**Comment by CurRonyx** [comment]
What's Game ID?

**Comment by ghost** [comment]
Well now I'm compiling .. as for the error on the Git .. do you have git installed?

https://git-scm.com/downloads

**Comment by ghost** [comment]
Error :/

**Comment by Donothan73** [comment]
yeah I have git installed, I even uninstalled and then reinstalled

**Comment by JonnycatMeow** [comment]
to fix the git thing do git clone https://github.com/brightfyregit/Indie-Cross-Public.git

**Comment by MemeHoovy** [comment]
You git clone the repository https://github.com/brightfyregit/Indie-Cross-Public.git
In order to fix the issue
Now close it

**Comment by JonnycatMeow** [comment]
> You git clone the repository https://github.com/brightfyregit/Indie-Cross-Public.git In order to fix the issue Now close it

bruh i just said that
