### ISSUE TITLE
Error during compiling

### ISSUE THREAD

**Issue by ghost** [brightfyregit/Indie-Cross-Public#9]
During compilation, when it gets to Main, this error comes out:

![error](https://user-images.githubusercontent.com/109472165/183301048-8ad1c822-44cf-4d9b-b989-81b2b3aaf51c.png)

**Comment by ghost** [comment]
well i'm italian, so if you want to understand the error, use a translator.

**Comment by RonyxDumb** [comment]
What

**Comment by RonyxDumb** [comment]
come on!
